{% set name = "ott-jax" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 75493682b930bf04d94e7e3097665d2b91001d98c92a13d406d4c271d1bf049e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - jax >=0.4.0
    - jaxopt >=0.8
    - lineax >=0.0.5
    - numpy >=1.20.0

test:
  imports:
    - ott

about:
  home: https://github.com/ott-jax/ott
  license: Apache-2.0
  license_file: LICENSE
  summary: Optimal Transport Tools in JAX
  description: |
    A JAX powered library to compute optimal transport at scale and on accelerators.
  doc_url: https://ott-jax.readthedocs.io
  dev_url: https://github.com/ott-jax/ott

extra:
  recipe-maintainers:
    - michalk8
    - marcocuturi
