{% set name = "ott-jax" %}
{% set version = "0.5.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5547faddb0312164c6fad23545ac558b08d0bafdae364315c6c4f6f4ecdc9d38

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - jax >=0.4.0
    - jaxopt >=0.8
    - lineax >=0.0.7
    - optax >=0.2.4
    - numpy >=1.20.0
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - ott

about:
  home: https://github.com/ott-jax/ott
  license: Apache-2.0
  license_file: LICENSE
  summary: Optimal Transport Tools in JAX
  description: |
    A JAX powered library to compute optimal transport at scale and on accelerators.
  doc_url: https://ott-jax.readthedocs.io
  dev_url: https://github.com/ott-jax/ott

extra:
  recipe-maintainers:
    - michalk8
    - marcocuturi
