{% set name = "ott-jax" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ott-jax-{{ version }}.tar.gz
  sha256: 071fdd5fca23558bbb0c71f7251de5549ea40cca25c108262c01e6f3de0ba5b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - jax >=0.1.67
    - jaxlib >=0.1.47
    - jaxopt >=0.5.5
    - numpy >=1.18.4,!=1.23.0
    - flax >=0.5.2
    - optax >=0.1.1

test:
  imports:
    - ott
  # enable on `lineax` is available
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/ott-jax/ott
  license: Apache-2.0
  license_file: LICENSE
  summary: Optimal Transport Tools in JAX
  description: |
    A JAX powered library to compute optimal transport at scale and on accelerators.
  doc_url: https://ott-jax.readthedocs.io
  dev_url: https://github.com/ott-jax/ott

extra:
  recipe-maintainers:
    - michalk8
    - marcocuturi
