{% set name = "ott-jax" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ott-jax-{{ version }}.tar.gz
  sha256: 20da1e501cfb94e0bf87a7695e1a90ccd38fd16e7d508df097286e6e2d77a261

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - jax >=0.4.0
    - jaxlib >=0.4.0
    - jaxopt >=0.8
    - numpy >=1.20.0

test:
  imports:
    - ott

about:
  home: https://github.com/ott-jax/ott
  license: Apache-2.0
  license_file: LICENSE
  summary: Optimal Transport Tools in JAX
  description: |
    A JAX powered library to compute optimal transport at scale and on accelerators.
  doc_url: https://ott-jax.readthedocs.io
  dev_url: https://github.com/ott-jax/ott

extra:
  recipe-maintainers:
    - michalk8
    - marcocuturi
