{% set name = "ott-jax" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ott-jax-{{ version }}.tar.gz
  sha256: 949fd59a68750581425887f840565f014f31bd846494a8207ec2d836f60f19ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - jax >=0.1.67
    - jaxlib >=0.1.47
    - numpy >=1.18.4,!=1.23.0
    - matplotlib-base >=3.0.0
    - flax >=0.5.2
    - optax >=0.1.1
    - scipy >=1.7.0
    - importlib-metadata >=1.0
    - typing-extensions

test:
  imports:
    - ott
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ott-jax/ott
  license: Apache-2.0
  license_file: LICENSE
  summary: Optimal Transport Tools in Jax.
  description: |
    A JAX powered library to compute optimal transport at scale and on accelerators.
  doc_url: https://ott-jax.readthedocs.io
  dev_url: https://github.com/ott-jax/ott

extra:
  recipe-maintainers:
    - michalk8
    - marcocuturi
